#cloud-config
hostname: "${vm_name}.dev.wnet"
ssh_pwauth: True
runcmd:
  - mkdir -p "${mount_point}"
  - mkfs.ext4 /dev/sdb
  - mount /dev/sdb "${mount_point}"
  - echo "/dev/sdb ${mount_point} ext4 defaults 0 0" >> /etc/fstab"



